INSERT INTO workout (name) VALUES ('Cardio Blast');
INSERT INTO workout (name) VALUES ('Strength Training');
INSERT INTO workout (name) VALUES ('Yoga Flow');
INSERT INTO workout (name) VALUES ('HIIT Session');
INSERT INTO workout (name) VALUES ('Pilates Core');
INSERT INTO workout (name) VALUES ('CrossFit Challenge');
INSERT INTO workout (name) VALUES ('Zumba Dance');
INSERT INTO workout (name) VALUES ('Cycling Sprint');
INSERT INTO workout (name) VALUES ('Boxing Workout');
INSERT INTO workout (name) VALUES ('Stretch and Relax');